version: '2'
services:
  container:
    image: opentosca/container
    ports:
      - 1337:1337/tcp
    environment:
      - CONTAINER_HOSTNAME=container
      - CONTAINER_REPOSITORY_HOSTNAME=container-repository
      - ENGINE_PLAN_HOSTNAME=engine-plan
      - ENGINE_IA_HOSTNAME=engine-ia
    networks:
      - opentosca
  container-repository:
    image: opentosca/winery
    ports:
      - 8081:8080/tcp
    # volumes:
    #   - <path on host system>:/var/opentosca/repository
    networks:
      - opentosca
  ui:
    image: opentosca/ui
    ports:
      - 8088:8080/tcp
    networks:
      - opentosca
  engine-plan:
    image: opentosca/bps
    ports:
      - 9443:9443/tcp # https
      - 9763:9763/tcp # http
    environment:
      - ENGINE_PLAN_HOSTNAME=engine-plan
    networks:
      - opentosca
  engine-ia:
    image: opentosca/engine-ia
    ports:
      - 8090:8080/tcp
    networks:
      - opentosca
  winery:
    image: opentosca/winery
    ports:
      - 8080:8080/tcp
    # volumes:
    #   - <path on host system>:/var/opentosca/repository
    networks:
      - opentosca
  dind:
    image: jpetazzo/dind:latest
    privileged: true
    environment:
      - PORT=2375
      - DOCKER_DAEMON_ARGS=--dns 8.8.8.8 --dns 8.8.4.4 -D
    ports:
      - 9975:2375/tcp # dind
      #- 9990-9999:9990-9999/tcp # dind
    # volumes:
    #   - '/var/run/docker.sock:/var/run/docker.sock'
    networks:
      - opentosca
networks:
  opentosca:
    driver: bridge
