version: '2'

services:
  init-guac-db:
    image: guacamole/guacamole:0.9.14
    command: ["/bin/sh", "-c", "test -e /init/initdb.sql && echo 'init file already exists' || /opt/guacamole/bin/initdb.sh --postgres > /init/initdb.sql" ]
    volumes:
      - dbinit:/init
    labels:
      io.rancher.container.start_once: 'true'

  postgres:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - dbinit:/docker-entrypoint-initdb.d
      - dbdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${guacamole_db}
      POSTGRES_USER: ${guacamole_db_user}
      POSTGRES_PASSWORD: ${guacamole_db_password}
    depends_on:
      - init-guac-db

  guacd:
    image: guacamole/guacd:0.9.14
    restart: unless-stopped

  guac:
    image: guacamole/guacamole:0.9.14
    restart: unless-stopped
    environment:
      GUACD_HOSTNAME: guacd
      POSTGRES_HOSTNAME: postgres
      POSTGRES_DATABASE: ${guacamole_db}
      POSTGRES_USER: ${guacamole_db_user}
      POSTGRES_PASSWORD: ${guacamole_db_password}
    links:
     - guacd:guacd
    ports:
      - ${public_port}:8080/tcp

volumes:
  dbinit:
    driver: rancher-nfs
  dbdata:
    driver: rancher-nfs

