version: '2'
services:
  guac:
    scale: 1
    health_check:
      healthy_threshold: 2
      response_timeout: 2000
      port: 8080
      unhealthy_threshold: 3
      initializing_timeout: 60000
      interval: 2000
      strategy: recreate
      request_line: GET "/guacamole" "HTTP/1.0"
      reinitializing_timeout: 60000
  guacd:
    scale: 1
    health_check:
      healthy_threshold: 2
      response_timeout: 2000
      port: 4822
      unhealthy_threshold: 3
      initializing_timeout: 60000
      interval: 2000
      strategy: recreate
      reinitializing_timeout: 60000
  init-guac-db:
    scale: 1
  postgres:
    scale: 1
    health_check:
      healthy_threshold: 2
      response_timeout: 2000
      port: 5432
      unhealthy_threshold: 3
      initializing_timeout: 60000
      interval: 2000
      strategy: recreate
      reinitializing_timeout: 60000
.catalog:
  name: "apache-guacamole"
  version: "0.2-rancher1"
  description: " Apache Guacamole is a clientless remote desktop gateway. It supports standard protocols like VNC, RDP, and SSH."
  minimum_rancher_version: v0.46.0
  questions:
    - variable: "guacamole_db"
      label: "Postgres Database Name"
      description: "Your Postgres guacamole database name"
      default: "guacamole_db"
      required: true
      type: "string"
    - variable: "guacamole_db_user"
      label: "Postgres Database User"
      description: "Your Postgres guacamole user name"
      required: true
      default: "guacamole_db_user"
      type: "string"
    - variable: "guacamole_db_password"
      label: "MySQL Database Password"
      description: "Your Postgres guacamole user password. Defaults to \"guacamole_db_password\""
      required: true
      default: "guacamole_db_password"
      type: "password"
    - variable: "public_port"
      label: "Public Port"
      description: "The public port that Guacamole listens on, defaults to 8080"
      required: true
      default: 8080
      type: "int"
