version: '2'

services:
  # Create SQL scripts for configuring remote PostgresDB
  init-guac-db:
    image: guacamole/guacamole:0.9.14
    command: ["/bin/sh", "-c", "echo \"CREATE USER ${guacamole_db_user} WITH PASSWORD '${guacamole_db_password}';\" > /init/createdb.sql &&
                                echo \"CREATE DATABASE ${guacamole_db};\" >> /init/createdb.sql &&
                                echo \"GRANT ALL PRIVILEGES ON DATABASE ${guacamole_db} TO ${guacamole_db_user};\" >> /init/createdb.sql &&
                                /opt/guacamole/bin/initdb.sh --postgres > /init/initdb.sql" ]
    volumes:
      - dbinit:/init
    labels:
      io.rancher.container.start_once: 'true'

  # Run SQL init scripts on remote PostgresDB
  init-postgres-db:
    image: postgres:9.6-alpine
    volumes:
      - dbinit:/init
    command: ["/bin/sh", "-c", "echo ${postgres_host}:${postgres_port}:*:${postgres_user}:${postgres_password} > ~/.pgpass &&
                                echo ${postgres_host}:${postgres_port}:${guacamole_db}:${guacamole_db_user}:${guacamole_db_password} >> ~/.pgpass &&
                                chmod 600 ~/.pgpass &&
                                psql -h ${postgres_host} -p ${postgres_port} -w -U ${postgres_user} < /init/createdb.sql &&
                                psql -h ${postgres_host} -p ${postgres_port} -w -U ${guacamole_db_user} -d ${guacamole_db} < /init/initdb.sql" ]
    depends_on:
      - init-guac-db
    labels:
      io.rancher.container.start_once: 'true'

  guacamole-server:
    image: guacamole/guacd:0.9.14
    restart: unless-stopped

  guacamole-client:
    image: guacamole/guacamole:0.9.14
    restart: unless-stopped
    environment:
      GUACD_HOSTNAME: guacamole-server
      POSTGRES_HOSTNAME: ${postgres_host}
      POSTGRES_PORT: ${postgres_port}
      POSTGRES_DATABASE: ${guacamole_db}
      POSTGRES_USER: ${guacamole_db_user}
      POSTGRES_PASSWORD: ${guacamole_db_password}
    ports:
      - ${public_port}:8080/tcp
    depends_on:
      - init-postgres-db

volumes:
  dbinit:
    driver: rancher-nfs

