version: '2'
catalog:
  name: "Alien4Cloud"
  version: "1.4.3.1-rancher0"
  description: |
    Alien4Cloud Stack
  uuid: alien4cloud-0
  questions:
    - variable: "public_port"
      label: "Public Port"
      description: "The public port that Alien4Cloud listens on, defaults to 8088"
      required: true
      default: 8088
      type: "int"

services:
  alien4cloud:
    scale: 1
    health_check:
      port: ${public_port}
      interval: 5000
      unhealthy_threshold: 3
      request_line: ''
      healthy_threshold: 2
      response_timeout: 5000
      strategy: none
